### ISSUE TITLE
Make work with shadow DOM

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/news-vj-sharetools#20]
Other components have a `scope` parameter passed to their constructor.

Looks like this one got missed: https://jira.dev.bbc.co.uk/browse/NEWSSPEC-20055

Have now raised https://jira.dev.bbc.co.uk/browse/NEWSSPEC-21601

**Comment by eagerterrier** [comment]
this has been done in https://github.com/bbc/news-vj-sharetools/tree/v5.2.0
